import * as Fi from "react-icons/fi";

const ICON_MAP: Record<string, React.ComponentType<{ className?: string }>> = {
  FiFileText: Fi.FiFileText,
  FiFile: Fi.FiFile,
  FiFilePlus: Fi.FiFilePlus,
  FiClipboard: Fi.FiClipboard,
  FiCheckCircle: Fi.FiCheckCircle,
  FiCheckSquare: Fi.FiCheckSquare,
  FiCheck: Fi.FiCheck,
  FiList: Fi.FiList,
  FiBriefcase: Fi.FiBriefcase,
  FiFolder: Fi.FiFolder,
  FiFolderPlus: Fi.FiFolderPlus,
  FiUser: Fi.FiUser,
  FiUsers: Fi.FiUsers,
  FiUserPlus: Fi.FiUserPlus,
  FiUserCheck: Fi.FiUserCheck,
  FiCalendar: Fi.FiCalendar,
  FiMail: Fi.FiMail,
  FiSend: Fi.FiSend,
  FiMessageCircle: Fi.FiMessageCircle,
  FiMessageSquare: Fi.FiMessageSquare,
  FiClock: Fi.FiClock,
  FiActivity: Fi.FiActivity,
  FiTarget: Fi.FiTarget,
  FiFlag: Fi.FiFlag,
  FiAward: Fi.FiAward,
  FiStar: Fi.FiStar,
  FiHeart: Fi.FiHeart,
  FiBook: Fi.FiBook,
  FiBookOpen: Fi.FiBookOpen,
  FiArchive: Fi.FiArchive,
  FiPackage: Fi.FiPackage,
  FiBox: Fi.FiBox,
  FiInbox: Fi.FiInbox,
  FiLayers: Fi.FiLayers,
  FiLayout: Fi.FiLayout,
  FiGrid: Fi.FiGrid,
  FiBarChart2: Fi.FiBarChart2,
  FiPieChart: Fi.FiPieChart,
  FiTrendingUp: Fi.FiTrendingUp,
  FiDollarSign: Fi.FiDollarSign,
  FiCreditCard: Fi.FiCreditCard,
  FiSettings: Fi.FiSettings,
  FiTool: Fi.FiTool,
  FiShield: Fi.FiShield,
  FiLock: Fi.FiLock,
  FiKey: Fi.FiKey,
  FiFilter: Fi.FiFilter,
  FiSearch: Fi.FiSearch,
  FiEdit: Fi.FiEdit,
  FiEdit2: Fi.FiEdit2,
  FiSave: Fi.FiSave,
  FiPrinter: Fi.FiPrinter,
  FiDownload: Fi.FiDownload,
  FiUpload: Fi.FiUpload,
  FiLink: Fi.FiLink,
  FiShare2: Fi.FiShare2,
  FiPaperclip: Fi.FiPaperclip,
  FiHome: Fi.FiHome,
  FiGlobe: Fi.FiGlobe,
  FiMap: Fi.FiMap,
  FiMapPin: Fi.FiMapPin,
  FiTruck: Fi.FiTruck,
  FiGift: Fi.FiGift,
  FiZap: Fi.FiZap,
  FiRefreshCw: Fi.FiRefreshCw,
  FiLifeBuoy: Fi.FiLifeBuoy,
  FiHelpCircle: Fi.FiHelpCircle,
  FiInfo: Fi.FiInfo,
  FiAlertCircle: Fi.FiAlertCircle,
  FiTag: Fi.FiTag,
  FiDatabase: Fi.FiDatabase,
  FiServer: Fi.FiServer,
  FiCode: Fi.FiCode,
  FiCloud: Fi.FiCloud,
  FiUmbrella: Fi.FiUmbrella,
};

export const PROCESS_ICON_OPTIONS = Object.keys(ICON_MAP);

export function ProcessIcon({ icon, className }: { icon: string; className?: string }) {
  const Comp = ICON_MAP[icon] ?? Fi.FiFileText;
  return <Comp className={className} />;
}
